service: message-sub
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: '*'

plugins:
  - serverless-esbuild
  - serverless-offline

functions:
  subMessage:
    handler: src/functions/subMessage/handler.main
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:${aws:accountId}:test-jhonpedro-sns
          topicName: test-jhonpedro-sns

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define: {}
    platform: node
    concurrency: 10
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001
